# Generated by Django 4.2.5 on 2024-08-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_association_officials_name_association_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
