# Generated by Django 4.2.5 on 2024-08-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_association_linkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='linkname',
            field=models.CharField(default='Link', max_length=100),
        ),
    ]
