# Generated by Django 4.2.5 on 2024-09-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_notes1_1_link_notes1_2_link_notes2_1_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes2_2',
            name='link',
            field=models.FileField(upload_to='notes'),
        ),
        migrations.AlterField(
            model_name='pastpaper1_1',
            name='link',
            field=models.FileField(upload_to='notes'),
        ),
        migrations.AlterField(
            model_name='pastpaper1_2',
            name='link',
            field=models.FileField(upload_to='notes'),
        ),
    ]
