# Generated by Django 5.1.1 on 2024-09-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_alter_notes2_2_link_alter_pastpaper1_1_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes2_2',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pastpaper1_1',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pastpaper1_2',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
