# Generated by Django 4.2.5 on 2024-08-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0002_faith_officials_name_faith_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='faith',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
