# Generated by Django 4.2.5 on 2024-08-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0003_faith_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='faith',
            name='linkname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
