# Generated by Django 4.2.5 on 2024-08-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0010_house_officials_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='House Name', max_length=100)),
                ('available_rooms', models.IntegerField(default=0)),
            ],
        ),
    ]
