# Generated by Django 4.2.5 on 2024-08-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0011_availableroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableRoom',
        ),
    ]
